language: node_js
node_js:
    - 17
sudo: false
script:
    - npm test
deploy:
    provider: heroku
    api_key:
        secure: iKbRTgWVxLdIdOVwkyn7Bp3ZycUXGdUo3UshcPkDUG1l/rxarKNbt+QVtqJ9JD3MC3CrpEWoCncam1Ja/roxP6jhS/eC3H7VhPx/nQQaeAM3Q6zuqRgWWIQ4a/Fw/+3fyB58EM/DoT9dh4OfdGZTh347W3Foxf3hNaFY3ygSWH9OO5uTgeg/rk5Oqq1CnQ5g33TPdcz9hjfQeUMxHsqMFZ3DZQCt/F10ue5kzyqOSKkNfD2GsVc2bihBz7rC+bn/ePaDAmtl7fwJAsR9CSKs3MPS5nablgjiuv5PqVWKvhXNuQt898dPb6Nu4h4mNSeQA/BPBRpjnc7QemNUdZ46xXjD1zkil24i3PWLn5x6V+tL1ee7zq/LN+g0ibUL17yOlBsQvoSqhIFGgdq8jE8qhxSODUMqtwO8Y3g02M4ts6PUQNddgW1aheeofPNLvj1/NLxJDKmlDvZVToRcaFVE2Bl3LAtJub9+pXej/QVp4AjeVyRlRGeFBXAgzitgXVYkRNobbXfumenRdRRg9HlG7FvdRb26/zygjLyCgptTxJeCwU71dUCTffZJNkH8GiccxztFovPcVirJDaohRfXwwfOXedeIjLlvF6fYrF07jllMvCCQtI1Nos/Mk9+HbDO2oFHwqcd7BH1y+dREEWL7lBUMxnGZNQ/6ZQgNXPn181M=
    app: sprint-devops-miguel
    skip_cleanup: 'true'
