language: node_js
node_js:
    - 17
sudo: false
script:
    - npm test
deploy:
    provider: heroku
    api_key:
        secure: bQlKyUtBqATvEHyCeASwEr7XmRTzeS1zn/mD4XXty39St217ev7Ty+pXcQvWrFGTzPDs0OlqKZQYASZ49WiHH1T/dasZTCWpW1oH9AOiHeAmESrKaTHOSOxj5FiugDcX53PElzza9+KJ2cG6T8SSFgNFZ1yjBH4J+tTuwpwTVjbehJRiBig3q0/Y7dvsDbkEnu0vX0WnwOabvx55qheUfQ5DdnljTOP0CLPBgysqNCVIIssOC2us4zN3T4itG4rYjD4gipguCFuC/mo9NcoqeFxrYmqIg6sSrdtwhFDsaGmxngGm5aD0IMZtjl7OCe5J6jx5SRXdoiBHcREixYyHdZgKxGTecUJIdn5n6WcewZNNC021a+Uw15FCyUvFlnjniGD6Ya+Rp4N4uP0jNY0Voimxv5x0/zOZterjWSMmuYQTYKuwtQoZam6zhbYQcpTeRrGOtqZPAn8H7HmMsUZnyC6Wx0C2eBnYEN2VI0vcLrGoXVHmcxX0M517iaL3bxa2or0+of9A/n2fMu1SjCCXKUq9x5ofOZhIDZ6TcFuhuDmq0b9YIqkIyRS4Km2IpIWvlFbBMKB3w1St9vx/M4lrqpN9ai7y844I27ErQ/d2KpNrbIQjZzVWMG7Z5XHFV7gUkKztgj+J+fwCZorX4aiGBu8l4O2ZpkEx6K8PkLAyRcM=
    app: sprint-devops-miguel
    edge: true
