language: node_js
node_js:
    - 17
sudo: false
script:
    - npm test
deploy:
    provider: heroku
    api_key:
        secure: FsK/LGIyC91L1+8PrmuBDIqdPdKXVANYy818ZVmxWIBSdrDD/inBY7o3eUAfqmga/yxBtPa6nVjlNXYbqzkfcwj2etSQofzac32xwsbr9QjVyyErzaDjVJnIfaNqJM6IcJrBKZzAPfjdPwaMM3tMMUiZmNhCyO47k5KuZFCCXJ6Xcms8wlG47vVfxoGETrZe9B5JRP/WXblyihHDApcolag5uYu55TlK8e3X9NOzH9Q/iza0k2OUrJpI5vlILMAcwirwv+bBMlKVH2qklN7qja1Qd8bdbMabt03FN7eKB0E+7j1Ad7W9ucd/X1EVovSL19p2RhiDY5VEDQsxjaShHKdOgxP4V6LdEDcgltL/p6dSMZvgq7hXmD09LjEVVjmUaoyUhHFO6M3HnTB1dGA0qx1JMD6/e/gynrFyocRnQRcUWYSFMXKZNkGvkITjArO6+4+J9cbmB5ahk4fAxS9EbvDcdz0tBD0Hg0/C+YtNWA3d55Z6XPO3zMITM8dpACFZHVwdAjaliaTIn4FAFSjDsVPQlCvEmozzTZQfojXsQ+f91hqgTA92TiBPQ9KLLtv1s9O5W3fWBcvWSRn2WtIOJxDiWAmuay1qEySFbvYfd8bavi6NHsBnEuh/GFSw11wBt3FCkwwd0sE1LuD8JUY8RDetW2k31q0sbqtHyrwVRpE=
    app: sprint-devops-miguel
    edge: true
